### ISSUE TITLE
Error after IDE Upgrade

### ISSUE THREAD

**Issue by dustingraham** [tangzx/IntelliJ-Lua#8]
Just got prompted to upgrade phpstorm.

```PhpStorm 2017.1
Build #PS-171.3780.104, built on March 21, 2017
Licensed to AJA Video Systems / Dustin Graham
Subscription is active until January 3, 2018
JRE: 1.8.0_112-release-736-b13 x86
JVM: OpenJDK Server VM by JetBrains s.r.o
Windows 8.1 6.3```

It states that the error is from this lua ide plugin, if it's not sorry I can't tell. Error given.

```Method com/tang/intellij/lua/codeInsight/LuaParameterHintsProvider.getHintInfo(Lcom/intellij/psi/PsiElement;)Lcom/intellij/codeInsight/hints/HintInfo; is abstract```

Details.

```Method com/tang/intellij/lua/codeInsight/LuaParameterHintsProvider.getHintInfo(Lcom/intellij/psi/PsiElement;)Lcom/intellij/codeInsight/hints/HintInfo; is abstract
java.lang.AbstractMethodError: Method com/tang/intellij/lua/codeInsight/LuaParameterHintsProvider.getHintInfo(Lcom/intellij/psi/PsiElement;)Lcom/intellij/codeInsight/hints/HintInfo; is abstract
	at com.tang.intellij.lua.codeInsight.LuaParameterHintsProvider.getHintInfo(LuaParameterHintsProvider.java)
	at com.intellij.codeInsight.hints.ParameterHintsPassFactory$ParameterHintsPass.a(ParameterHintsPassFactory.java:122)
	at com.intellij.codeInsight.hints.ParameterHintsPassFactory$ParameterHintsPass.a(ParameterHintsPassFactory.java:94)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.intellij.codeInsight.hints.ParameterHintsPassFactory$ParameterHintsPass.doCollectInformation(ParameterHintsPassFactory.java:94)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1153)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:431)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.d(PassExecutorService.java:430)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:406)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:242)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:404)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:165)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)


java.lang.AbstractMethodError: Method com/tang/intellij/lua/codeInsight/LuaParameterHintsProvider.getHintInfo(Lcom/intellij/psi/PsiElement;)Lcom/intellij/codeInsight/hints/HintInfo; is abstract
	at com.tang.intellij.lua.codeInsight.LuaParameterHintsProvider.getHintInfo(LuaParameterHintsProvider.java)
	at com.intellij.codeInsight.hints.ParameterHintsPassFactory$ParameterHintsPass.a(ParameterHintsPassFactory.java:122)
	at com.intellij.codeInsight.hints.ParameterHintsPassFactory$ParameterHintsPass.a(ParameterHintsPassFactory.java:94)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.intellij.codeInsight.hints.ParameterHintsPassFactory$ParameterHintsPass.doCollectInformation(ParameterHintsPassFactory.java:94)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1153)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:431)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.d(PassExecutorService.java:430)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:406)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:242)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:404)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:165)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)```

**Comment by tangzx** [comment]
The API was be changed in v2017, I will upgrade plugin as soon as possible

**Comment by tangzx** [comment]
Hi, dustingraham
here's new version `1.0.6`. you can try `LuaIDE_IDEA171_1.0.6.zip` for `InerlliJ-IDEA 2017.1`

**Comment by dustingraham** [comment]
This looks great! No more errors. Nice work @tangzx 

![looksgood](https://cloud.githubusercontent.com/assets/1414400/24389427/52e88544-1336-11e7-9a8b-2dde97166ec1.png)
